config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :buildings do
  resources :apartments 
  end
  root 'buildings#index'
end

app/models/apartment.rb
class Apartment < ApplicationRecord
  belongs_to :building
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/building.rb
class Building < ApplicationRecord
  has_many :apartments #Importante que sea en plural la relación de modelos
  validates :name, presence: true
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :set_apartment, only: %i[ show edit update destroy ]
  
  def index 
    @building = Building.find(params[:building_id])
    @apartments = @building.apartments
  end

  def new
    @apartment = Apartment.new
    @building = Building.find(params[:building_id]) #Pluck busca todos los registros del edificio
  end

  def show
    @building = Building.find(params[:building_id])
    @apartment = Apartment.find(params[ :id ])
  end

  def create
      building = Building.find(params[:building_id])
      @apartment = Apartment.new(apartment_params.merge(building_id: building.id))
  
      respond_to do |format|
        if @apartment.save
          format.html { redirect_to building_apartments_path(building.id), notice: "Apartment was successfully created." }
          format.json { render :show, status: :created, location: @apartment }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @apartment.errors, status: :unprocessable_entity }
        end
      end
    end

    private
    def set_apartment
      @apartment = Apartment.pluck(:name, :id)
    end

    #Strong params
    def apartment_params
      params.require(:apartment).permit(:number, :building_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_action :set_building, only: %i[ show edit update destroy ]
  
  def index
    @buildings = Building.all
  end

  def new
    @building = Building.new
    @apartment = Apartment.pluck(:id, :name)
  end

  def show
    @building = Building.find(params[:id]) #Paréntesis es opcional
  end

  def create
  @building = Building.new(building_params)

  respond_to do |format|
    if @building.save
      format.html { redirect_to @building, notice: "Building was successfully created." }
      format.json { render :show, status: :created, location: @building }
    else
      format.html { render :new, status: :unprocessable_entity }
      format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_building
    @building = Building.find(params[:id])
  end

  #Strong params
  def building_params
    params.require(:building).permit(:name)
  end

end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/views/apartments/index.html.erb
<h2 class= 'text-center text-secondary'>Apartments</h2>

<br>
<table class="table">
  <thead>
        <tr>
          <th scope="col">Number of Apartments</th> 
          <th scope="col">Name of Building</th> 
          <th colspan="3"></th>
        </tr>
   </thead>
        <tbody>
            <% @apartments.each do |apartment| %>
            <tr>
                <td><%= apartment.number %></td> 
                <td><%= apartment.building.name %></td>
                <td><%=link_to 'Show aparment', building_apartment_path(@building.id, apartment.id)%></td>
            </tr> <% end %>
        </tbody> 
</table>

<div class="text-left my-4">
<%= link_to 'Back', building_path(@building.id), class: 'btn btn-secondary' %>
</div>

app/views/apartments/new.html.erb
<h1 class="text-center text-secondary my-5">New Apartment</h1>
<div class="container">

<%= form_with(model:[@building, @apartment]) do |form| %>
  <% if @apartment.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@apartment.errors.count, "error") %> prohibited this building from being saved:</h4>

      <ul>
        <% @apartment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= form.text_field :number, class:'form-control', placeholder: 'Number of apartments' %><br>
  <br><br>
  <div class="text-center">
  <%= form.submit 'Submit', class: 'btn btn-secondary' %>
  </div>
  <br>
<% end %>
</div>

app/views/apartments/show.html.erb
<h1 class= 'text-center text-secondary'>Apartments <%= @apartment.number %> of <%= @building.name %> </h1>

<div class="text-left">
  <td><%=link_to 'Back', building_apartments_path(@building.id), class: 'btn btn-secondary'%></td>
</div>

app/views/buildings/index.html.erb
<h1 class="text-center text-secondary">Buildings</h1>

<br>
<table class="table">
 <thead>
    <tr>
      <th>Building</th>
      <th>Id</th> 
      <th colspan="3"></th>
    </tr>
 </thead>

  <tbody>
    <% @buildings.each do |building| %>
    <tr>
      <td><%= building.name %></td>
      <td><%= "id:#{building.id}" %></td>
      <td><%=link_to 'Show', building%></td>
    </tr> 
    <% end %>
  </tbody>
</table>

<div class="text-left my-4">
<%= link_to 'New Building', new_building_path, class: 'btn btn-secondary' %>
</div>

app/views/buildings/new.html.erb
<h1 class="text-center text-secondary my-5">New Building</h1>
<div class="container">

<%= form_with(model: @building) do |form| %>
  <% if @building.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@building.errors.count, "error") %> prohibited this building from being saved:</h4>

      <ul>
        <% @building.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= form.text_field :name, class:'form-control', placeholder: 'Name of building' %><br>
  <br><br>
  <div class="text-center">
  <%= form.submit 'Submit', class: 'btn btn-secondary' %>
  </div>
  <br>
<% end %>
</div>

app/views/buildings/show.html.erb
<h2 class= 'text-center text-secondary'>Buildings <%= @building.name %></h2> 

<div class="text-center">
  <%=link_to 'Show departments', building_apartments_path(@building.id), class: 'btn btn-light'%>
  <%=link_to 'New apartment', new_building_apartment_path(@building.id), class: 'btn btn-light'%>
</div>
<br>
<div class="text-left">
  <%=link_to 'Back', buildings_path, class: 'btn btn-secondary'%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApartmentBuilding</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!--Link Boostrap-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class= 'container'>
    <%= yield %>
  </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>  
  </body>
</html>